const fs = require('fs');
const path = require('path');

const dir = 'd:\\pdfcraft\\src\\lib\\pdf\\processors';

const replacements = [
  { search: 'PDFCraft Trusted TSA Authority', replace: 'SPVN Tech Trusted TSA Authority' },
  { search: 'PDFCraft Secure Group', replace: 'SPVN Tech Secure Group' },
  { search: 'setProducer(\'PDFCraft\')', replace: 'setProducer(\'SPVN Tech PDF Tools\')' },
  { search: 'publisher || \'PDFCraft\'', replace: 'publisher || \'SPVN Tech\'' },
  { search: 'appID: \'PDFCraft/1.0\'', replace: 'appID: \'SPVN Tech/1.0\'' },
  { search: 'bookTitle: \'PDFCraft Bound Book\'', replace: 'bookTitle: \'SPVN Tech Bound Book\'' },
  { search: '// Generated by PDFCraft Form Logic Designer', replace: '// Generated by SPVN Tech Form Logic Designer' },
  { search: 'Producer\'), pdfLib.PDFString.of(\'PDFCraft Sanitizer', replace: 'Producer\'), pdfLib.PDFString.of(\'SPVN Tech Sanitizer' },
  { search: 'https://pdfcraft.org', replace: 'https://spvntech.in' }
];

const files = fs.readdirSync(dir);
for (const file of files) {
  if (file.endsWith('.ts')) {
    const filePath = path.join(dir, file);
    let content = fs.readFileSync(filePath, 'utf8');
    let modified = false;
    
    for (const { search, replace } of replacements) {
      if (content.includes(search)) {
        content = content.replaceAll(search, replace);
        modified = true;
      }
    }
    
    if (modified) {
      fs.writeFileSync(filePath, content, 'utf8');
      console.log(`Updated ${file}`);
    }
  }
}
